# CMake generated Testfile for 
# Source directory: E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable
# Build directory: E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-changelist__WIN32 "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/build/bin/test-changelist")
set_tests_properties(test-changelist__WIN32 PROPERTIES  ENVIRONMENT "EVENT_SHOW_METHOD=1" _BACKTRACE_TRIPLES "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1214;add_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1280;add_backend_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;0;")
add_test(test-eof__WIN32 "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/build/bin/test-eof")
set_tests_properties(test-eof__WIN32 PROPERTIES  ENVIRONMENT "EVENT_SHOW_METHOD=1" _BACKTRACE_TRIPLES "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1214;add_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1280;add_backend_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;0;")
add_test(test-fdleak__WIN32 "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/build/bin/test-fdleak")
set_tests_properties(test-fdleak__WIN32 PROPERTIES  ENVIRONMENT "EVENT_SHOW_METHOD=1" _BACKTRACE_TRIPLES "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1214;add_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1280;add_backend_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;0;")
add_test(test-init__WIN32 "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/build/bin/test-init")
set_tests_properties(test-init__WIN32 PROPERTIES  ENVIRONMENT "EVENT_SHOW_METHOD=1" _BACKTRACE_TRIPLES "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1214;add_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1280;add_backend_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;0;")
add_test(test-time__WIN32 "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/build/bin/test-time")
set_tests_properties(test-time__WIN32 PROPERTIES  ENVIRONMENT "EVENT_SHOW_METHOD=1" _BACKTRACE_TRIPLES "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1214;add_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1280;add_backend_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;0;")
add_test(test-weof__WIN32 "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/build/bin/test-weof")
set_tests_properties(test-weof__WIN32 PROPERTIES  ENVIRONMENT "EVENT_SHOW_METHOD=1" _BACKTRACE_TRIPLES "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1214;add_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1280;add_backend_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;0;")
add_test(test-dumpevents__WIN32 "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/build/bin/test-dumpevents" "|" "C:/Python34/python.exe" "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/test/check-dumpevents.py")
set_tests_properties(test-dumpevents__WIN32 PROPERTIES  ENVIRONMENT "EVENT_SHOW_METHOD=1" _BACKTRACE_TRIPLES "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1227;add_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1280;add_backend_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;0;")
add_test(regress__WIN32 "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/build/bin/regress")
set_tests_properties(regress__WIN32 PROPERTIES  ENVIRONMENT "EVENT_SHOW_METHOD=1" _BACKTRACE_TRIPLES "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1249;add_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1280;add_backend_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;0;")
add_test(regress__WIN32_debug "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/build/bin/regress")
set_tests_properties(regress__WIN32_debug PROPERTIES  ENVIRONMENT "EVENT_SHOW_METHOD=1;EVENT_DEBUG_MODE=1" _BACKTRACE_TRIPLES "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1255;add_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1280;add_backend_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;0;")
add_test(test-ratelim__group_lim "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/build/bin/test-ratelim" "-g" "30000" "-n" "30" "-t" "100" "--check-grouplimit" "1000" "--check-stddev" "100")
set_tests_properties(test-ratelim__group_lim PROPERTIES  _BACKTRACE_TRIPLES "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1291;add_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;0;")
add_test(test-ratelim__con_lim "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/build/bin/test-ratelim" "-c" "1000" "-n" "30" "-t" "100" "--check-connlimit" "50" "--check-stddev" "50")
set_tests_properties(test-ratelim__con_lim PROPERTIES  _BACKTRACE_TRIPLES "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1300;add_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;0;")
add_test(test-ratelim__group_con_lim "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/build/bin/test-ratelim" "-c" "1000" "-g" "30000" "-n" "30" "-t" "100" "--check-grouplimit" "1000" "--check-connlimit" "50" "--check-stddev" "50")
set_tests_properties(test-ratelim__group_con_lim PROPERTIES  _BACKTRACE_TRIPLES "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1309;add_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;0;")
add_test(test-ratelim__group_con_lim_drain "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/build/bin/test-ratelim" "-c" "1000" "-g" "35000" "-n" "30" "-t" "100" "-G" "500" "--check-grouplimit" "1000" "--check-connlimit" "50" "--check-stddev" "50")
set_tests_properties(test-ratelim__group_con_lim_drain PROPERTIES  _BACKTRACE_TRIPLES "E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;1320;add_test;E:/Team Building/learn/libevent-2.1.11-stable/libevent-2.1.11-stable/CMakeLists.txt;0;")
